---
title: 'Project 123d: Walleye Management on the Lower Green and Colorado Rivers'
author:
  affiliation: Utah Division of Wildlife Resources
  name: Christopher Michaud
date: "03 September 2021"
output:
  html_document:
    fig_caption: no
    keep_md: yes
  word_document: default
---





































# {.tabset .tabset-fade .tabset-pills}

### Abstract

Utah Division of Wildlife Resources (UDWR, Moab, UT) expended 74.9 hours of electrofishing effort under Project 123d to remove nonnative walleye from the upper Colorado River Basin in 2021. Crews focused removal efforts within specific subreaches where walleye catch rates are highest: downstream of Tusher Diversion (River Mile (RM)  - ) and Lower Gray Canyon (RM  - ) on the Green River and Lower Westwater Canyon (RM  - ) on the Colorado River. A total of 0 walleye and 0 smallmouth bass were encountered throughout sampling in 2021. While walleye encounters were similar to recent years, smallmouth bass captures on the Lower Colorado River were substantially more frequent. <br><br>



```{=html}
<template id="b24eec5a-a35b-4c21-bb44-512ec9b4c9bb"><style>
.tabwid table{
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-spacing: 0;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-6f7ad84a{table-layout:auto;border-collapse:collapse;width:70%;}.cl-6f75410a{font-family:'Helvetica';font-size:14pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6f754128{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6f754132{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-6f7553c0{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6f7553ca{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-6f7582c8{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f7582dc{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f7582e6{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f7582fa{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f7582fb{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f758304{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-6f75830e{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-6f7ad84a'><thead><tr style="overflow-wrap:break-word;"><td  colspan="7"class="cl-6f7582fb"><p class="cl-6f7553c0"><span class="cl-6f75410a">Table 1. Effort summary by reach in 2021</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f75830e"><p class="cl-6f7553c0"><span class="cl-6f754128">Reach</span></p></td><td class="cl-6f758304"><p class="cl-6f7553ca"><span class="cl-6f754128">Start Date</span></p></td><td class="cl-6f758304"><p class="cl-6f7553ca"><span class="cl-6f754128">End Date</span></p></td><td class="cl-6f758304"><p class="cl-6f7553ca"><span class="cl-6f754128">Days Sampled</span></p></td><td class="cl-6f758304"><p class="cl-6f7553ca"><span class="cl-6f754128">Sampling Effort (hr)</span></p></td><td class="cl-6f758304"><p class="cl-6f7553ca"><span class="cl-6f754128">Temperature Range (°C)</span></p></td><td class="cl-6f758304"><p class="cl-6f7553ca"><span class="cl-6f754128">Discharge Range (cfs)</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-6f7582dc"><p class="cl-6f7553c0"><span class="cl-6f754132"></span></p></td><td class="cl-6f7582c8"><p class="cl-6f7553ca"><span class="cl-6f754132">23 March 2021</span></p></td><td class="cl-6f7582c8"><p class="cl-6f7553ca"><span class="cl-6f754132">02 June 2021</span></p></td><td class="cl-6f7582c8"><p class="cl-6f7553ca"><span class="cl-6f754132">11</span></p></td><td class="cl-6f7582c8"><p class="cl-6f7553ca"><span class="cl-6f754132">31.4</span></p></td><td class="cl-6f7582c8"><p class="cl-6f7553ca"><span class="cl-6f754132"> 9.8 - 21.3</span></p></td><td class="cl-6f7582c8"><p class="cl-6f7553ca"><span class="cl-6f754132">1,830 - 8,810</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-6f7582fa"><p class="cl-6f7553c0"><span class="cl-6f754132"></span></p></td><td class="cl-6f7582e6"><p class="cl-6f7553ca"><span class="cl-6f754132">29 April 2021</span></p></td><td class="cl-6f7582e6"><p class="cl-6f7553ca"><span class="cl-6f754132">12 August 2021</span></p></td><td class="cl-6f7582e6"><p class="cl-6f7553ca"><span class="cl-6f754132">13</span></p></td><td class="cl-6f7582e6"><p class="cl-6f7553ca"><span class="cl-6f754132">43.5</span></p></td><td class="cl-6f7582e6"><p class="cl-6f7553ca"><span class="cl-6f754132">14.4 - 25.1</span></p></td><td class="cl-6f7582e6"><p class="cl-6f7553ca"><span class="cl-6f754132">2,150 - 7,990</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="7dfaf5b2-98b8-436b-a1ae-08bd585c56f5"></div>
<script>
var dest = document.getElementById("7dfaf5b2-98b8-436b-a1ae-08bd585c56f5");
var template = document.getElementById("b24eec5a-a35b-4c21-bb44-512ec9b4c9bb");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

```

___

<br><br> 

<center>

```{=html}
<div id="htmlwidget-5c9da815c2be427d48f7" style="width:672px;height:480px;" class="leaflet html-widget"></div>
<script type="application/json" data-for="htmlwidget-5c9da815c2be427d48f7">{"x":{"options":{"minZoom":1,"maxZoom":52,"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}},"preferCanvas":false,"bounceAtZoomLimits":false,"maxBounds":[[[-90,-370]],[[90,370]]]},"calls":[{"method":"addProviderTiles","args":["Esri.WorldImagery","Esri.WorldImagery","Esri.WorldImagery",{"errorTileUrl":"","noWrap":false,"detectRetina":false,"pane":"tilePane"}]},{"method":"addProviderTiles","args":["OpenTopoMap","OpenTopoMap","OpenTopoMap",{"errorTileUrl":"","noWrap":false,"detectRetina":false,"pane":"tilePane"}]},{"method":"addProviderTiles","args":["CartoDB.Positron","CartoDB.Positron","CartoDB.Positron",{"errorTileUrl":"","noWrap":false,"detectRetina":false,"pane":"tilePane"}]},{"method":"addProviderTiles","args":["OpenStreetMap","OpenStreetMap","OpenStreetMap",{"errorTileUrl":"","noWrap":false,"detectRetina":false,"pane":"tilePane"}]},{"method":"createMapPane","args":["line",430]},{"method":"addPolylines","args":[[[[{"lng":[-110.140399864168,-110.140402028218,-110.141781884326,-110.143334737592,-110.144768412075,-110.146201684443,-110.14644772418,-110.145279637973,-110.143731234978,-110.141974169259,-110.140670695984,-110.140021234478,-110.139735924598,-110.139727568015,-110.139719211226,-110.13977657035,-110.139710281651,-110.139518227496,-110.139439391402,-110.139604200478,-110.139953154103,-110.140606034261,-110.141369826114,-110.142130546154,-110.142669232934,-110.143338805207,-110.14403047194,-110.144581961831,-110.145080003309,-110.145604147921,-110.14627123721,-110.147006121945,-110.147752242634,-110.148704634127,-110.148854953535,-110.14858849607,-110.148199366517,-110.14819343802,-110.147868310817,-110.147543061456,-110.147213600724,-110.146626755469,-110.145470413956,-110.144001559602,-110.142441375248,-110.140820964678,-110.139658069727,-110.13952361173,-110.140474142857,-110.141757231387,-110.142794996056,-110.143836318265,-110.14546599192,-110.147237721,-110.14908154851,-110.150915092936,-110.152672211904,-110.153825385672,-110.153995980812,-110.153600003361,-110.152464918515,-110.150938751524,-110.149307139172,-110.147615378615,-110.145886754333,-110.144097415093,-110.142329552447,-110.140563327648,-110.138937460321,-110.138122658838,-110.137775248874,-110.137735164993,-110.138007208874,-110.138728136667,-110.139500771925,-110.140186524086,-110.140785022323,-110.141787551454,-110.142874678744,-110.143988902327,-110.144765394899,-110.145900279788,-110.14757158683,-110.149129874676,-110.150036587034,-110.150067830233,-110.149802179335,-110.149609849921,-110.148787268536,-110.148384587453,-110.149327672175,-110.150039062496,-110.150585675882,-110.150441142944,-110.150061300932,-110.149481518931,-110.148656162969,-110.147492745828,-110.146240508045,-110.144819259193,-110.143355408908,-110.142016053629,-110.140695023231,-110.139808187008,-110.139242780336,-110.138618516065,-110.138196367807,-110.138433510635,-110.139840319831,-110.141442629579,-110.143183854458,-110.144980650489,-110.146788107274,-110.148573417376,-110.150126048915,-110.151183888777,-110.15202895465,-110.152449791269,-110.152168909735,-110.150951234091,-110.149298326092,-110.14754188694,-110.145889761457,-110.144288366914,-110.142653553673,-110.141022221235,-110.139916198043,-110.139065124251,-110.138222345339,-110.137448858322,-110.136691507804,-110.136079436848,-110.13543217048,-110.134839901296,-110.134495198839,-110.134182011758,-110.134721124486,-110.13609832328,-110.136255141774,-110.135531016451,-110.136591943469,-110.13802085704,-110.139793975878,-110.141645130063,-110.143496785526,-110.145352993875,-110.147169950289,-110.148931402311,-110.150715830212,-110.152568178145,-110.15442272807,-110.156241951683,-110.158018597689,-110.159808839994,-110.161622034586,-110.163440983391,-110.165260492096,-110.167096064991,-110.168945536672,-110.170793161656,-110.172651025092,-110.174333689983,-110.175536003281,-110.176543200892,-110.177202170689,-110.177805552649,-110.178353780993,-110.17855263644,-110.178354176782,-110.177798039088,-110.177101910568,-110.176330289936,-110.176345748663,-110.177532955751,-110.178598280964,-110.179167695203],"lat":[39.0804656923088,39.0804597448406,39.0795881270604,39.0787894884081,39.0778686736329,39.0769452178801,39.0755773194207,39.0744971972231,39.0737496871998,39.0732744366767,39.0723282146664,39.070974449424,39.0695453632287,39.0680951031928,39.0666448428024,39.0651956851834,39.063748346666,39.0623076181356,39.0608679233461,39.0594237642916,39.0580072175951,39.0566636398297,39.0553352430672,39.0540121331318,39.052624778559,39.0512726064295,39.0499262377079,39.0485432832873,39.0471463806677,39.0457559889721,39.0444032586486,39.0430706701852,39.0417426309393,39.0404963710469,39.0390546803639,39.0376243737327,39.0362189700719,39.0347631057632,39.0333351289083,39.031907581372,39.0304803063456,39.0291194398936,39.0280141766243,39.0271293104335,39.0263427774949,39.0256336442227,39.0246019700911,39.0231734049647,39.0220087842582,39.0209821454615,39.0197784012932,39.0186124553379,39.0179355062635,39.0175066061645,39.0174491587097,39.0172447914631,39.0168438493382,39.0157729936087,39.0143385295824,39.0129372096042,39.0118255920087,39.011002424087,39.0103090856482,39.0097084387237,39.0091870120058,39.008793575353,39.008345256599,39.0078927824359,39.0072045225388,39.0059364094071,39.0045117054675,39.0030623283556,39.0016279645287,39.0003128341761,38.9989957348127,38.9976494155127,38.9962768085097,38.9950650628976,38.9938888007719,38.9927292885886,38.9914160859862,38.9902930386582,38.9896823064657,38.9888935744081,38.9877074905123,38.9862723240181,38.9848371984666,38.983396806098,38.9821532055311,38.9807375444683,38.9795751879041,38.9782370154428,38.9768532042278,38.9754266388776,38.9740095403287,38.9726345057531,38.9713462041659,38.9702175579942,38.9691461208805,38.9682243349485,38.9673365221026,38.9663314895967,38.965312562608,38.9641629641803,38.9627903604073,38.9614278288799,38.9600165711661,38.9587285165589,38.957799148934,38.957069316103,38.9565859285563,38.9562183341101,38.9558862529214,38.9554886808687,38.9548074790126,38.95362343998,38.9523361707461,38.9509242482625,38.949527562588,38.948461901177,38.9478085665818,38.9473394813767,38.9466990844881,38.9459655696861,38.9452771882995,38.9446165597966,38.9434347706178,38.9421453824979,38.9408530136353,38.9395354624175,38.9382116157465,38.9368433303726,38.9354848101767,38.934115173196,38.9326894826616,38.9312624010888,38.930077041886,38.9291316579507,38.9277892368303,38.9264559371208,38.9253595228869,38.9244420272131,38.9240460166896,38.9239357172963,38.9238988808923,38.9239322290604,38.9241354443863,38.9245922491488,38.9249907043695,38.9250147147801,38.9249848188994,38.9252469521222,38.9256699237582,38.9260508714393,38.9263640284971,38.9266535873025,38.9269388195872,38.9270297036725,38.9269198047768,38.9267918038616,38.9268769549549,38.9263933011341,38.9252960258894,38.9240817395109,38.9227252565476,38.9213540994228,38.9199692827892,38.9185544869892,38.9171129139188,38.9157346792738,38.9143932741381,38.9130865788433,38.9116641906558,38.9105917153515,38.9094095363366,38.9080487946025]}],[{"lng":[-110.179167695203,-110.178595340138,-110.176911206618,-110.175193486448,-110.173560071259,-110.17194047234,-110.170604463575,-110.169232163718,-110.167899712886,-110.166643700267,-110.165434482454,-110.164659627108,-110.163994879544,-110.163187226367,-110.16205093823,-110.160967255495,-110.160095598419,-110.159545351727,-110.159516402076,-110.159884057772,-110.160281076785,-110.160715445293,-110.161046294592,-110.161410334788,-110.161861897846,-110.161884941722,-110.161787868403,-110.161700082983,-110.161840241198,-110.162218405672,-110.162393574578,-110.162568735872,-110.162730924371,-110.162867291601,-110.163021079981,-110.162766449644,-110.161820329235,-110.160421352604,-110.158708851348,-110.156871751322,-110.155066668588,-110.153271094727,-110.151590149002,-110.150158646833,-110.148837160994,-110.147688776257,-110.146520678978,-110.145291647871,-110.143675708555,-110.141883499808,-110.140062518343,-110.138473999253,-110.137499393451,-110.136866779334,-110.136441360956,-110.13601595891,-110.135199166765,-110.134847313116,-110.135775506164,-110.13671438145,-110.137467817087,-110.138239184972,-110.139052396992,-110.13990812682,-110.140769985192,-110.141655699507,-110.142458280991,-110.143278108567,-110.14442394389,-110.145178833863,-110.145648079326,-110.145858986441,-110.146044356686,-110.14568634331,-110.14430141655,-110.142828113141,-110.141354846176,-110.139890243874,-110.138369405839,-110.136640968273,-110.134794737538,-110.13294330639,-110.131091879761,-110.129241313777,-110.127391452912,-110.126631709789,-110.125191376502,-110.12351005502,-110.121806849934,-110.120396729707,-110.119200342393,-110.119363230342,-110.120468892775,-110.121981454431,-110.12331293913,-110.124250184959,-110.124663315691,-110.12433300309,-110.122688890446,-110.120847869859,-110.119006858698,-110.117165856964,-110.115362563003,-110.113566123406,-110.111888260711,-110.110655237753,-110.109741964541,-110.108895909458,-110.107983973009,-110.107072068463,-110.106312545982,-110.105863765858,-110.105482959821,-110.105186238723,-110.105032769899,-110.104968221075,-110.104476141434,-110.104967858289,-110.106241308102,-110.107564103018,-110.109098663008,-110.11065666899],"lat":[38.9080487946024,38.906776984568,38.9062249354692,38.9056908690779,38.9050024769241,38.9042994599931,38.9032925127622,38.9023159793808,38.9013080824232,38.9002418387638,38.8991413181432,38.8978378903179,38.8964834228477,38.8951822023013,38.8940413102157,38.8928704783671,38.8915911000861,38.8902198185091,38.8887596055517,38.8873409854969,38.8859246939769,38.8845141983695,38.8830873886238,38.8816662779139,38.8802601937336,38.8788270423569,38.8773789838107,38.8759314796268,38.8745000604111,38.8730841036581,38.8716403418317,38.8701965793098,38.8687524160789,38.8673067003101,38.8658613787905,38.8644303404847,38.8631835774224,38.8622671541008,38.861751138472,38.8618049415115,38.8621264244389,38.8624759706427,38.8630722900565,38.8639941244974,38.8649995690473,38.8661383525828,38.8672647873904,38.8683349148648,38.8690473851308,38.8693743357185,38.8691292381143,38.8684349470158,38.8672349577464,38.8658819011764,38.8644704325318,38.8630589621917,38.8617657659355,38.8604052704841,38.8591615820157,38.857916666151,38.8565923927455,38.8552729499149,38.8539700579936,38.8526839831365,38.8514002292114,38.8501254955663,38.8488231953605,38.8475361432117,38.8463995470344,38.8450804162199,38.8436780799051,38.8422430021908,38.8408034122749,38.8394677766555,38.838512770208,38.8376325601652,38.83675233182,38.8358617543476,38.8350430660795,38.8345844223858,38.8344479027388,38.8343713454173,38.8342947587938,38.8342090869152,38.8341175187496,38.8329042329208,38.8320560990009,38.8314500064421,38.8308823079366,38.8299724150106,38.8289996582787,38.8275550808158,38.8264553369397,38.8256249933411,38.8246158063592,38.8233874888563,38.8219799868059,38.8206131457144,38.8199549416928,38.8197825324136,38.8196100942187,38.8194376271086,38.8191114763148,38.8187548881778,38.8181592875283,38.817087992658,38.8158429942882,38.8145545368403,38.8132922472293,38.812029950611,38.8107198986457,38.8093124597068,38.807894422609,38.8064632752253,38.8050205798934,38.8035707163445,38.8022424843733,38.8008596920222,38.7998371495548,38.7988219387239,38.7980181571081,38.7972401468675]}]]],null,"Tusher",{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}},"pane":"line","stroke":true,"color":"#0000FF","weight":5,"opacity":0.9,"fill":false,"fillColor":"#6666FF","fillOpacity":1,"smoothFactor":1,"noClip":false},"<div class='scrollableContainer'><table class=mapview-popup id='popup'><tr class='coord'><td><\/td><th><b>Feature ID&emsp;<\/b><\/th><td>2&emsp;<\/td><\/tr><tr><td>1<\/td><th>nm_rvr&emsp;<\/th><td>Green River&emsp;<\/td><\/tr><tr><td>2<\/td><th>cd_rvr&emsp;<\/th><td>GR&emsp;<\/td><\/tr><tr><td>3<\/td><th>nm_basin&emsp;<\/th><td>Green&emsp;<\/td><\/tr><tr><td>4<\/td><th>GEOMETRY&emsp;<\/th><td>sfc_MULTILINESTRING&emsp;<\/td><\/tr><tr><td>5<\/td><th>reach&emsp;<\/th><td>Tusher Reach&emsp;<\/td><\/tr><\/table><\/div>",{"maxWidth":800,"minWidth":50,"autoPan":true,"keepInView":false,"closeButton":true,"closeOnClick":true,"className":""},"2",{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},{"stroke":true,"weight":8,"opacity":1,"fill":false,"fillOpacity":0,"bringToFront":false,"sendToBack":false}]},{"method":"addScaleBar","args":[{"maxWidth":100,"metric":true,"imperial":true,"updateWhenIdle":true,"position":"bottomleft"}]},{"method":"addHomeButton","args":[-110.179167695203,38.7972401468675,-110.104476141434,39.0804656923088,true,"Tusher","Zoom to Tusher","<strong> Tusher <\/strong>","bottomright"]},{"method":"addLegend","args":[{"colors":["#0000FF"],"labels":["Tusher"],"na_color":null,"na_label":"NA","opacity":1,"position":"topright","type":"factor","title":"","extra":null,"layerId":null,"className":"info legend","group":"Tusher"}]},{"method":"addPolylines","args":[[[[{"lng":[-109.163075100928,-109.163075100928,-109.164896216179,-109.166730746338,-109.168572235913,-109.170423303016,-109.172263825214,-109.174083360662,-109.175850957023,-109.177452495251,-109.178808877607,-109.179820314382,-109.180491287746,-109.180991797755,-109.181620167538,-109.182323234877,-109.182838892262,-109.183435329563,-109.184407035509,-109.185819048027,-109.187005852371,-109.18796535399,-109.188814510202,-109.190479225361,-109.19215767914,-109.193410472455,-109.194812453967,-109.196066289613,-109.197361409595,-109.198772210245,-109.200278063093,-109.20196217833,-109.203809668008,-109.205660942638,-109.207507221386,-109.20921352855,-109.210742029456,-109.212103490044,-109.212930090334,-109.213273512224,-109.214338964311,-109.215662918417,-109.217047480301,-109.21827453068,-109.219617329635,-109.221228441178,-109.222839586009,-109.224500532951,-109.226192050385,-109.227869934988,-109.22954784966,-109.231261418786,-109.233018012941,-109.23480388013,-109.236649130862,-109.238292956843,-109.240117111999,-109.241965246324,-109.243759291683,-109.245395396186,-109.246933233616,-109.248398423964,-109.249111786229,-109.249663706548,-109.249904747982,-109.248944649836,-109.247851812901,-109.246659712885,-109.245419182829,-109.245073760043,-109.244091547274,-109.242621706408,-109.240858792986,-109.239086220277,-109.23770856849,-109.237644189091,-109.238956940766,-109.240639920538,-109.241476215097,-109.240775200944,-109.239310783091,-109.237536906496,-109.235716233087,-109.233954961441,-109.232159715508,-109.230998230445,-109.230550752879,-109.230371274832,-109.230291056398,-109.230597247079,-109.230626250208,-109.229198918575,-109.228143162438,-109.22747422937,-109.226425599358,-109.225778579924,-109.226044586963,-109.226444069091,-109.226974821811,-109.227787055456,-109.228824542005,-109.230229519751,-109.231652016472,-109.233187524727,-109.234817830705,-109.23643826691,-109.238254488459,-109.239998417447,-109.241515402865,-109.243137229154,-109.244704524763,-109.246024585564,-109.247025627214,-109.246821879928,-109.247110897543,-109.247915021503,-109.248230652469,-109.24815620637,-109.247935890822,-109.247146724271,-109.246346846086,-109.24505181921,-109.243424958989,-109.241684511492,-109.239859781207,-109.238061734472,-109.236263706813,-109.234465698229,-109.232841310847,-109.232105757225,-109.231152942376,-109.230306169547,-109.230651113952,-109.232385840692,-109.234050254821,-109.235788627067,-109.237598892181,-109.239441925791,-109.241028254247,-109.242730521627,-109.244272647566,-109.245584002316,-109.246687829041,-109.247602108554,-109.249243035777,-109.25105352488,-109.252909829493,-109.254545155448,-109.256373105664,-109.257834274531,-109.258516654005,-109.258647924316,-109.258486825368,-109.258398173299,-109.258420476084,-109.258719876404,-109.25932152085,-109.260556005564,-109.262128162816,-109.263504381036,-109.264265482498,-109.264861408298,-109.26595829147,-109.266896535761,-109.268083192386,-109.269310929829,-109.270510689185,-109.271545919681,-109.272365477253,-109.273129614941,-109.273735898791,-109.27440152971,-109.275162778175,-109.276156367472,-109.277530282732,-109.279041808495,-109.280678166928,-109.281878234907,-109.282611332353,-109.282565031654,-109.282279918088,-109.282190904935,-109.282019516874,-109.281324630921,-109.280235000154,-109.279346934442,-109.279148912826,-109.279882249726,-109.280848174634,-109.282079535567,-109.283454388145,-109.284565043971,-109.28543331068,-109.286075849197,-109.285553500496,-109.285029603824,-109.285198446429,-109.28512828354,-109.284989557597,-109.285355151031,-109.284909786174,-109.284058862171,-109.28337314272,-109.282762676087,-109.281922886846,-109.281426505062,-109.281496163266,-109.28205170905,-109.282868658026,-109.283961344587,-109.285214197036,-109.285987580087,-109.287016488704,-109.288639950306,-109.290486616758,-109.292336739285,-109.294184199841,-109.296031667288,-109.297876738916,-109.299708503396,-109.301509950344,-109.303360007658,-109.305205012275,-109.307049302569,-109.308893586525,-109.310740416897,-109.312463361293,-109.314035945634,-109.315466434071,-109.315810607238,-109.315110544883,-109.314386130431,-109.313584108904,-109.312886391866,-109.312799879316,-109.313100556556,-109.313917506879,-109.315647439496,-109.317445416942,-109.319220829479,-109.320758846009,-109.322250977153,-109.324047658215,-109.325865538933,-109.327670472622,-109.329292067789,-109.330600363,-109.331527858901,-109.332126078097,-109.332675111388,-109.33307749678,-109.334114805707,-109.335823120634,-109.337603265925,-109.339252456445,-109.340603540511,-109.341518232092,-109.341694636197,-109.34161443787,-109.341697281476,-109.341439004422,-109.340311153191,-109.338850401662,-109.337631888375,-109.336760727766,-109.335986707154,-109.334930882867,-109.334316054371,-109.333655112222,-109.333792831616,-109.333808595177,-109.333189696543,-109.332533499991,-109.332043600424,-109.331405117614,-109.330587250411,-109.32956674236,-109.328148642832,-109.326943340787,-109.325670173033,-109.324771443096,-109.323811784241,-109.323107469949,-109.321923614792,-109.321192934474,-109.322095640078,-109.322450624497,-109.322594523823,-109.323534312818,-109.325165177357,-109.32659502663,-109.327897592902,-109.328832742329,-109.329746937938,-109.331104043724,-109.332775693815,-109.334510307491,-109.33629485806,-109.337949243989,-109.339373336758,-109.340532251214,-109.341381177534,-109.341811794802,-109.342234012275,-109.342894311508,-109.343958695191,-109.345384980115,-109.346903910347,-109.348559000127,-109.350388459141,-109.352155753119,-109.353594544378,-109.354435233543,-109.355236168446,-109.356575708827,-109.358310991216,-109.360095610315,-109.361681130345,-109.362497235426,-109.363342225165,-109.364777254347,-109.366154677323,-109.367487398586,-109.368745440785,-109.369640744414,-109.370492369305,-109.370464962381,-109.370516830212,-109.370620381699,-109.37177652066,-109.373515035696,-109.375222257105,-109.377042396749,-109.378864440649,-109.379907096632,-109.380524116925,-109.381635512086,-109.383209079088,-109.385041398057,-109.386763181818,-109.388230030637,-109.389542247448,-109.390756941811,-109.391623474737,-109.392086514242,-109.391929090192,-109.39190315507,-109.392390238441,-109.392974872545,-109.393781703257,-109.394446409352,-109.395967621269,-109.397748250041,-109.399555054086,-109.401208525382,-109.402299571884,-109.403692056858,-109.405221173735,-109.405808331251,-109.406590480585,-109.407206204659,-109.407997774684,-109.409637349235,-109.410710207474,-109.412414222894,-109.414219751305,-109.415255042832,-109.415148023676,-109.415726654348,-109.416616916586,-109.418340080486,-109.418744384331,-109.419473761857,-109.420246374577,-109.421008975379,-109.422272746939,-109.424089635157,-109.425874795215,-109.427311149184,-109.4290471779,-109.430825089838,-109.432608482831,-109.434075476711,-109.435327231097,-109.437143039986,-109.438829475764,-109.440563240615,-109.442346852852,-109.444173486711,-109.445874410743,-109.446806197835,-109.447503504258,-109.448952379486,-109.450778890798,-109.452495223966,-109.453980135865,-109.455662866287,-109.45698311363,-109.458345063104,-109.459803793696,-109.461504029757,-109.463297603941,-109.465127950404,-109.466899962846,-109.468625398277,-109.470373913266,-109.472118337215,-109.47395865909,-109.475807546581,-109.477607898032,-109.479374293943,-109.48102811608,-109.482321184401,-109.483728999077,-109.485080787921,-109.486570335523,-109.487827627978,-109.489249966696,-109.490712483734,-109.491881503162,-109.493669265695,-109.495428157731,-109.49708009146,-109.497691088791,-109.499084211046,-109.499929358717,-109.499962605076,-109.50003733732,-109.500166744647,-109.500438625436,-109.500869778267,-109.501289769353,-109.502059029981,-109.503128603639,-109.503996610142,-109.50474140976,-109.505094056103,-109.506053826415,-109.506685690029,-109.506578225853,-109.50621209636,-109.505884072796,-109.505443992534,-109.504182730088,-109.502668254295,-109.500913449125,-109.499090387601,-109.497329030138,-109.495674845535,-109.494065767851,-109.492539273956,-109.491026324414,-109.489345523843,-109.487626518751,-109.485880235713,-109.4840554348,-109.482519484402,-109.481058582812,-109.479488486248,-109.478015423608,-109.477221862605,-109.477290996529,-109.47814073578,-109.478688221208,-109.479548971904,-109.480397910974,-109.481268075625,-109.48252214397,-109.484070689577,-109.485598063417,-109.487059322487,-109.488462740796,-109.490235279052,-109.492042986564,-109.493851858395,-109.495561623805,-109.497334044667,-109.499100010774,-109.500662470847,-109.502274847045,-109.503887184637,-109.505536195798,-109.507239510128,-109.508863273045,-109.510491845116,-109.512137315271,-109.513726980899,-109.515313852406,-109.516891001254,-109.518468117398,-109.519992446002,-109.521453804031,-109.522915126225,-109.524361186852,-109.525782263552,-109.527222083552,-109.528698905318,-109.530228958282,-109.531707538242,-109.533062749349,-109.534281060228,-109.53570361823,-109.536949535576,-109.538225274959,-109.539833124377,-109.541657090233,-109.543500432062,-109.545309109502,-109.546906105659,-109.548335469348,-109.549536073793,-109.550784072841,-109.552196825662,-109.553731708571,-109.555456626525,-109.557236972046,-109.558472963345,-109.559101319113,-109.559518838929,-109.559692887398,-109.559866927986,-109.560393440396,-109.56100261087,-109.561801983818,-109.56293712686,-109.564563162343],"lat":[38.9828338311125,38.9828338311125,38.9827010268915,38.9829225596519,38.983098860805,38.9831799808815,38.983002441608,38.9827707611761,38.9823500326595,38.9816115256833,38.9806379349455,38.979441578386,38.9780933729467,38.9767013039366,38.9753397214105,38.9739969222541,38.972605085124,38.9712350004848,38.9700233021592,38.969089711032,38.9679766348234,38.9667372311444,38.9654509409299,38.96541449583,38.9651373162817,38.9640776095395,38.9631394383876,38.9620713273623,38.9610324022772,38.9600896827639,38.9592435309271,38.9588302750072,38.9588657562145,38.9587639419616,38.958611181588,38.9591216091439,38.9599389396267,38.96092509853,38.9621195552588,38.9635233186724,38.9646794248114,38.965689876183,38.9666186323462,38.9677067649079,38.9687000699367,38.9694217317255,38.9701433719384,38.9707880690551,38.9713865691051,38.9720082615769,38.9726299305302,38.9731832445769,38.9736528562445,38.974042699498,38.9742098706098,38.9748333215388,38.9751067512416,38.9750382983199,38.9746766649223,38.9740314717348,38.9732185021924,38.9723457836703,38.9710118574045,38.9696274528199,38.9682015385742,38.9669755755415,38.965802924126,38.9646934753419,38.9636148681195,38.9622173590039,38.9610258219374,38.9601404015832,38.9598211655145,38.959445248121,38.9585316001695,38.9571613212262,38.9562499413689,38.9556674378382,38.9544531825201,38.9531185472809,38.9524011422618,38.9519742259499,38.9517922242691,38.9513174811994,38.9509624149176,38.9499296597443,38.9485272029535,38.9470846096971,38.9456405510812,38.9442108686624,38.9429661704122,38.9421265468722,38.9409497035467,38.9396248231944,38.9384451404835,38.9371367485705,38.9357058373461,38.9342903205293,38.9329036525084,38.9316126250113,38.9304107438364,38.9294653736987,38.9285344148771,38.9277197246337,38.927043604895,38.9263963569978,38.9265156431693,38.9260585064459,38.9252300230876,38.9245252222011,38.9237495599973,38.9227437736532,38.9215726681322,38.9201324666078,38.91872652137,38.9174412123661,38.9160127253107,38.9145724115866,38.9131328421992,38.9120034803215,38.9107105319669,38.9097891793075,38.9091018905782,38.9086076509892,38.9083759051037,38.9080176081924,38.9076592839748,38.9073009324518,38.9066442692104,38.9053164442778,38.9040750319998,38.9027970371804,38.901554016431,38.9010620534066,38.9004221686403,38.8999202843212,38.899591218902,38.8994397262984,38.8987703055412,38.8981928199461,38.8974044147199,38.8963784547991,38.895216311358,38.8939905059778,38.8933474437168,38.8930434018939,38.893030682171,38.8924126518092,38.8921707979478,38.8914144563845,38.8900857963711,38.8886679098917,38.8872233644208,38.8857766683504,38.8843266785746,38.8829017205008,38.881555516438,38.8805121156933,38.879746755964,38.8787888702013,38.8774697157255,38.8760969139209,38.8749285159196,38.8736776381292,38.8725678527853,38.8714814062412,38.870375228923,38.8691765520786,38.8678770098856,38.8665565723328,38.8651869004678,38.863835509969,38.8625135712487,38.8612935273239,38.860321190328,38.8594953614287,38.8588143569457,38.857718619744,38.8564180069748,38.8549858093759,38.8535536838174,38.852105497778,38.8506708227689,38.8493394746325,38.8481540258857,38.8468888475196,38.8454861065579,38.84416075146,38.8429425995081,38.8419234294464,38.8409567226852,38.8398130298207,38.8385322512139,38.8371976845839,38.8358494818377,38.8345211338119,38.8330802385265,38.8316332376761,38.8301875019863,38.8287943426527,38.8274052070059,38.8261178424237,38.8247868884668,38.8234206821485,38.8221488934636,38.8207521324853,38.8193155563667,38.8179503437278,38.8166522258161,38.8154860080631,38.8144322636078,38.8131159393676,38.8119166623077,38.8112715365548,38.8112695537842,38.8113360161889,38.8114485485318,38.8115610517766,38.8116969718178,38.8119108947444,38.8121543749509,38.812067847298,38.811931509402,38.8117881603973,38.811644782096,38.8115326916829,38.8110244399274,38.8102721796237,38.8093528002547,38.8079645868506,38.806623005694,38.8052884362758,38.8039822190311,38.8026439781896,38.801207004826,38.7997786620157,38.7985192726716,38.7980094265764,38.7977129567925,38.7976192646982,38.7968185938027,38.796001907275,38.7956506422666,38.7954771055571,38.7957266741568,38.7963875206623,38.7973909026585,38.7986455012661,38.8000136372945,38.8013987369998,38.8027967267051,38.8039021941549,38.804205229426,38.8045620207083,38.8040400587037,38.8030526305448,38.8017939005816,38.8003605968282,38.7988998646934,38.7974968071891,38.7961010458617,38.7949542162116,38.7940800916383,38.7930326751728,38.791754731208,38.7904438298465,38.7892816134536,38.7879251748168,38.7865912951171,38.7851706179374,38.7837269583533,38.7823765760619,38.7810239324424,38.7796266792945,38.7782783298601,38.7769794711636,38.7757944580359,38.7748789474686,38.7737964706745,38.7727454553071,38.7714785625292,38.7702385827642,38.7689019709001,38.7680968359977,38.7668619522039,38.7657223065354,38.7643538729629,38.7629177787027,38.7617169345362,38.7610442433153,38.7601393493949,38.7591095146447,38.7578687161069,38.7566093213296,38.7556365537174,38.7558045271125,38.7562740887533,38.7559432818602,38.7552934653424,38.7544092015965,38.7532795332353,38.7520010108781,38.7505916006747,38.7491797750547,38.7478358451989,38.7466656505847,38.7457452644542,38.7449166184761,38.7442856651812,38.744185537916,38.7439517709972,38.7430674868956,38.7417757905323,38.7404695223693,38.7395429498354,38.739066122462,38.7387064334919,38.7379632885622,38.7367359887491,38.7354574550519,38.7345575654448,38.7335910225668,38.7325850682275,38.731521731459,38.730258599849,38.728966253916,38.7275201408257,38.7260722417618,38.72462885808,38.7235169783811,38.7231764227136,38.7234442871717,38.7233209051171,38.7233943632768,38.7223784282534,38.7210212076786,38.7198789735127,38.7192036661466,38.7191855664179,38.7186734847319,38.7178007054118,38.7167835045168,38.7157194914273,38.7144386558236,38.7130689496931,38.7116254162077,38.7101769801078,38.7087848497696,38.707402691577,38.7061189255188,38.7047847663897,38.7043355324307,38.7047225843109,38.7049409868416,38.7043856720908,38.7032278763045,38.7023680371967,38.7015612477685,38.7003219601221,38.6990263944622,38.6976634530921,38.6963874296659,38.696075719951,38.697139977492,38.6974952519399,38.6975642036469,38.6965497871368,38.6951509777652,38.6937818770018,38.6926309408761,38.6922147861399,38.6908173753046,38.689494476211,38.6882106651262,38.6869054448788,38.6859061177888,38.6857622098037,38.6854882093896,38.6845901681704,38.6841004244218,38.6836987959704,38.6833136035216,38.682704143294,38.6819122789558,38.6821390596896,38.6815551474478,38.6810493980593,38.6806967653219,38.6804696301772,38.6808558737544,38.6821052897867,38.6834468897731,38.6842206256318,38.6840889269998,38.6835941283296,38.6827306721779,38.682677141254,38.683687256108,38.6846663026173,38.6855577600769,38.6857664743548,38.6855148994228,38.685450323491,38.6850958388912,38.684574019211,38.684101192365,38.6836308802085,38.6834890869445,38.6835053904751,38.6832509593023,38.6828625741365,38.6823259943232,38.6812901691383,38.6803559573548,38.6793834397325,38.678515358815,38.677461958932,38.6765712402837,38.6757157932757,38.6746215141204,38.6742542252776,38.6738059241812,38.6731989828225,38.6719089469446,38.6709641043387,38.6696822655979,38.6683093472612,38.6668621537282,38.6654162206344,38.6639841768,38.6625742818045,38.6611628029456,38.6598676455927,38.6586863588556,38.6574177648668,38.6560931591453,38.6547504389815,38.6535123825553,38.6521676956004,38.6507306332544,38.6493094596967,38.6478975966555,38.6465108113869,38.6454620223695,38.6446345673209,38.6441880707764,38.6441691116339,38.6445867029221,38.6452335236656,38.6459448544933,38.6467618446502,38.6475911212036,38.6481784460264,38.6487115409389,38.6491869872697,38.649378912267,38.6487097635343,38.6478552850776,38.6471009778502,38.6462422008338,38.6449675938686,38.6435299903677,38.6422583112256,38.6408757947779,38.639601425043,38.6383197854444,38.6370421764262,38.6360195200958,38.6352804493624,38.6344789195581,38.6336678918535,38.6327909316797,38.632382316915,38.6320984088629,38.6318953206664,38.6313623434547,38.6309510081324,38.630528161906,38.6297555753227,38.6290466221015,38.6283373285702,38.6276896281715,38.627192717375,38.6265030582521,38.6258170109644,38.6251563784183,38.6244175901828,38.6236746978796,38.6229185559665,38.6221623920318,38.6213459315346,38.6204575446667,38.6195691386932,38.6186663913505,38.6177401582204,38.6168311380576,38.6159601455692,38.6151468413299,38.614276544689,38.6133019616672,38.6122116580595,38.6112945815346,38.610227441409,38.6091851438468,38.6085061447841,38.6083082791353,38.6083397685715,38.6086039271394,38.6092789500683,38.610197505347,38.6112933653042,38.6123626548942,38.6132968330577,38.6140903530517,38.6145291710535,38.6142640541136,38.6132476006127,38.6119103413296,38.610498573526,38.6090547313079,38.6076108883498,38.6062275690145,38.6048584431232,38.6035543052182,38.6024769085282,38.6019169298574]}],[{"lng":[-109.564715938334,-109.566385546612,-109.568105773285,-109.569826025891,-109.571618276382,-109.57342753571,-109.575238918444],"lat":[38.6019166757075,38.6022174563793,38.6027464081082,38.6032753349811,38.6036160607407,38.6039123317878,38.6041969750464]}]]],null,"Lower Westwater",{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}},"pane":"line","stroke":true,"color":"#CD0000","weight":5,"opacity":0.9,"fill":false,"fillColor":"#6666FF","fillOpacity":1,"smoothFactor":1,"noClip":false},"<div class='scrollableContainer'><table class=mapview-popup id='popup'><tr class='coord'><td><\/td><th><b>Feature ID&emsp;<\/b><\/th><td>1&emsp;<\/td><\/tr><tr><td>1<\/td><th>nm_rvr&emsp;<\/th><td>Colorado River&emsp;<\/td><\/tr><tr><td>2<\/td><th>cd_rvr&emsp;<\/th><td>CO&emsp;<\/td><\/tr><tr><td>3<\/td><th>nm_basin&emsp;<\/th><td>Upper Colorado&emsp;<\/td><\/tr><tr><td>4<\/td><th>GEOMETRY&emsp;<\/th><td>sfc_MULTILINESTRING&emsp;<\/td><\/tr><tr><td>5<\/td><th>reach&emsp;<\/th><td>Lower Westwater&emsp;<\/td><\/tr><\/table><\/div>",{"maxWidth":800,"minWidth":50,"autoPan":true,"keepInView":false,"closeButton":true,"closeOnClick":true,"className":""},"1",{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},{"stroke":true,"weight":8,"opacity":1,"fill":false,"fillOpacity":0,"bringToFront":false,"sendToBack":false}]},{"method":"addHomeButton","args":[-109.575238918444,38.6019166757075,-109.163075100928,38.9831799808815,true,"Lower Westwater","Zoom to Lower Westwater","<strong> Lower Westwater <\/strong>","bottomright"]},{"method":"addLayersControl","args":[["Esri.WorldImagery","OpenTopoMap","CartoDB.Positron","OpenStreetMap"],["Tusher","Lower Westwater"],{"collapsed":true,"autoZIndex":true,"position":"topleft"}]},{"method":"addLegend","args":[{"colors":["#CD0000"],"labels":["Lower Westwater"],"na_color":null,"na_label":"NA","opacity":1,"position":"topright","type":"factor","title":"","extra":null,"layerId":null,"className":"info legend","group":"Lower Westwater"}]},{"method":"addHomeButton","args":[-110.179167695203,38.6019166757075,-109.163075100928,39.0804656923088,true,null,"Zoom to full extent","<strong>Zoom full<\/strong>","bottomleft"]}],"limits":{"lat":[38.7972401468675,39.0804656923088],"lng":[-110.179167695203,-110.104476141434]},"fitBounds":[38.6019166757075,-110.179167695203,39.0804656923088,-109.163075100928,[]]},"evals":[],"jsHooks":{"render":[{"code":"function(el, x, data) {\n  return (\n      function(el, x, data) {\n      // get the leaflet map\n      var map = this; //HTMLWidgets.find('#' + el.id);\n      // we need a new div element because we have to handle\n      // the mouseover output separately\n      // debugger;\n      function addElement () {\n      // generate new div Element\n      var newDiv = $(document.createElement('div'));\n      // append at end of leaflet htmlwidget container\n      $(el).append(newDiv);\n      //provide ID and style\n      newDiv.addClass('lnlt');\n      newDiv.css({\n      'position': 'relative',\n      'bottomleft':  '0px',\n      'background-color': 'rgba(255, 255, 255, 0.7)',\n      'box-shadow': '0 0 2px #bbb',\n      'background-clip': 'padding-box',\n      'margin': '0',\n      'padding-left': '5px',\n      'color': '#333',\n      'font': '9px/1.5 \"Helvetica Neue\", Arial, Helvetica, sans-serif',\n      'z-index': '700',\n      });\n      return newDiv;\n      }\n\n\n      // check for already existing lnlt class to not duplicate\n      var lnlt = $(el).find('.lnlt');\n\n      if(!lnlt.length) {\n      lnlt = addElement();\n\n      // grab the special div we generated in the beginning\n      // and put the mousmove output there\n\n      map.on('mousemove', function (e) {\n      if (e.originalEvent.ctrlKey) {\n      if (document.querySelector('.lnlt') === null) lnlt = addElement();\n      lnlt.text(\n                           ' lon: ' + (e.latlng.lng).toFixed(5) +\n                           ' | lat: ' + (e.latlng.lat).toFixed(5) +\n                           ' | zoom: ' + map.getZoom() +\n                           ' | x: ' + L.CRS.EPSG3857.project(e.latlng).x.toFixed(0) +\n                           ' | y: ' + L.CRS.EPSG3857.project(e.latlng).y.toFixed(0) +\n                           ' | epsg: 3857 ' +\n                           ' | proj4: +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs ');\n      } else {\n      if (document.querySelector('.lnlt') === null) lnlt = addElement();\n      lnlt.text(\n                      ' lon: ' + (e.latlng.lng).toFixed(5) +\n                      ' | lat: ' + (e.latlng.lat).toFixed(5) +\n                      ' | zoom: ' + map.getZoom() + ' ');\n      }\n      });\n\n      // remove the lnlt div when mouse leaves map\n      map.on('mouseout', function (e) {\n      var strip = document.querySelector('.lnlt');\n      if( strip !==null) strip.remove();\n      });\n\n      };\n\n      //$(el).keypress(67, function(e) {\n      map.on('preclick', function(e) {\n      if (e.originalEvent.ctrlKey) {\n      if (document.querySelector('.lnlt') === null) lnlt = addElement();\n      lnlt.text(\n                      ' lon: ' + (e.latlng.lng).toFixed(5) +\n                      ' | lat: ' + (e.latlng.lat).toFixed(5) +\n                      ' | zoom: ' + map.getZoom() + ' ');\n      var txt = document.querySelector('.lnlt').textContent;\n      console.log(txt);\n      //txt.innerText.focus();\n      //txt.select();\n      setClipboardText('\"' + txt + '\"');\n      }\n      });\n\n      }\n      ).call(this.getMap(), el, x, data);\n}","data":null},{"code":"function(el, x, data) {\n  return (function(el,x,data){\n           var map = this;\n\n           map.on('keypress', function(e) {\n               console.log(e.originalEvent.code);\n               var key = e.originalEvent.code;\n               if (key === 'KeyE') {\n                   var bb = this.getBounds();\n                   var txt = JSON.stringify(bb);\n                   console.log(txt);\n\n                   setClipboardText('\\'' + txt + '\\'');\n               }\n           })\n        }).call(this.getMap(), el, x, data);\n}","data":null}]}}</script>
```
</center>

Figure 1. Removal reaches sampled during 2020: Lower Gray Canyon Reach (RM  - ), Tusher Reach (RM  - ) and Lower Westwater Reach (RM  and).

<br><br>


___


## Green River

<br><br>

<center>
<img src="/Users/christophermichaud/Documents/Projects/udwr-mfo_data-mgt/Reports/Assets/walleye-carlos.jpg" title="A photograph showing the Tusher diversion. It appears as a low head concrete dam with river water cascading over it. Concrete flow regulation gates are visible on the far side of the structure and a sunset over the desert landscape is in the background" alt="A photograph showing the Tusher diversion. It appears as a low head concrete dam with river water cascading over it. Concrete flow regulation gates are visible on the far side of the structure and a sunset over the desert landscape is in the background" width="5161" />
</center>  

The Tusher Diversion dam creates a semi-passable barrier on the Green River and delineates the upper boundary of the Tusher Walleye Management Reach.

___

<br><br>

### Tusher Reach

The Green River peaked at 9,450 cfs on 28 May 2021, measured on USGS gage 09315000, located at the town of Green River, Utah (Figure 2). Crews began sampling below Tusher Diversion on 23 March 2021 and ended on 02 June 2021. Main channel temperatures ranged between  9.8 - 21.3 °C during sampling (Table 1). Crews sampled between river miles  and  (Figure 1).

<br><br>




<center>
![This chart has title 'Figure 2. Discharge on the Green River, 2021'. It has the subtitle 'Sampling events noted with blue points'. It has x-axis '' with labels Jan, Apr and Jul. It has y-axis 'Discharge (cfs)' with labels 2500, 5000 and 7500. It has 2 layers. Layer 1 is a set of 1 line. Line 1 connects 245 points. Layer 1 has size set to 1. Layer 2 is a set of 11 points. Layer 2 has shape set to fillable circle. Layer 2 has size set to 4. Layer 2 has fill set to brilliant blue. Layer 2 has alpha set to 0.8. This figure is depicts the dates on which sampling occurred (points) and the river discharge (line) during the sampling period. The sampling dates and river discharge follow - March 23: 2010 cfs, March 30: 2050 cfs, April 05: 1830 cfs, April 13: 2470 cfs, April 19: 2360 cfs, May 11: 3350 cfs, May 18: 3190 cfs, May 19: 3020 cfs, May 20: 3150 cfs, May 27: 8810 cfs, June 02: 6580 cfs](123d_annual-rept_files/figure-html/gr-dis-fig-1.png)

```
## This chart has title 'Figure 2. Discharge on the Green River, 2021'.
## It has the subtitle 'Sampling events noted with blue points'.
## It has x-axis '' with labels Jan, Apr and Jul.
## It has y-axis 'Discharge (cfs)' with labels 2500, 5000 and 7500.
## It has 2 layers.
## Layer 1 is a set of 1 line.
## Line 1 connects 245 points.
## Layer 1 has size set to 1.
## Layer 2 is a set of 11 points.
## Layer 2 has shape set to fillable circle.
## Layer 2 has size set to 4.
## Layer 2 has fill set to brilliant blue.
## Layer 2 has alpha set to 0.8.
```

</center>


A total of 31.4 hours of effort were allocated to this reach and  101 walleye were removed (catch-per-unit-effort [cpue] = 3.22 fish-per-hour).  Walleye catch rates are similar to recent years (Table 4), but with increased effort substantially more walleye have been removed in 2019 and 2020 than previous years. Walleye total lengths within this reach were also similar to recent years (mean = 460 mm, range = 345 - 613 mm) (Figure 3). Additionally, researchers removed 37 smallmouth bass (cpue = 1.18 fish-per-hour) and 2 northern pike (cpue = 0.06 fish-per-hour) (Table 2). Native fish encounters are summarized in Table 3. 
  
<br><br>

<center>
```{=html}
<template id="4c3a6b2d-f903-4f6c-865d-e40e315f6923"><style>
.tabwid table{
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-spacing: 0;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-7058036e{table-layout:auto;border-collapse:collapse;width:50%;}.cl-70535300{font-family:'Helvetica';font-size:14pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7053531e{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-70535328{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-70535ee0{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-70535ef4{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-70538668{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7053867c{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-70538686{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-70538690{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7053869a{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7053869b{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-705386a4{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-705386a5{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-705386ae{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-7058036e'><thead><tr style="overflow-wrap:break-word;"><td  colspan="3"class="cl-705386a4"><p class="cl-70535ee0"><span class="cl-70535300">Table 2. Nonnative fish encounters within<br> the Tusher Reach, 2021</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-705386a5"><p class="cl-70535ee0"><span class="cl-7053531e">Common Name</span></p></td><td class="cl-705386ae"><p class="cl-70535ef4"><span class="cl-7053531e">Number of Fish Encountered</span></p></td><td class="cl-705386ae"><p class="cl-70535ef4"><span class="cl-7053531e">Fish-per-Hour</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-7053867c"><p class="cl-70535ee0"><span class="cl-70535328">walleye</span></p></td><td class="cl-70538668"><p class="cl-70535ef4"><span class="cl-70535328">101</span></p></td><td class="cl-70538668"><p class="cl-70535ef4"><span class="cl-70535328">3.22</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-70538690"><p class="cl-70535ee0"><span class="cl-70535328">smallmouth bass</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">37</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">1.18</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-70538690"><p class="cl-70535ee0"><span class="cl-70535328">green sunfish</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">34</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">1.08</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-70538690"><p class="cl-70535ee0"><span class="cl-70535328">white sucker</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">13</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">0.41</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-70538690"><p class="cl-70535ee0"><span class="cl-70535328">grass carp</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">5</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">0.16</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-70538690"><p class="cl-70535ee0"><span class="cl-70535328">northern pike</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">2</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">0.06</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-70538690"><p class="cl-70535ee0"><span class="cl-70535328">channel catfish</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">1</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">0.03</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-70538690"><p class="cl-70535ee0"><span class="cl-70535328">gizzard shad</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">1</span></p></td><td class="cl-70538686"><p class="cl-70535ef4"><span class="cl-70535328">0.03</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7053869b"><p class="cl-70535ee0"><span class="cl-70535328">unidentified</span></p></td><td class="cl-7053869a"><p class="cl-70535ef4"><span class="cl-70535328">1</span></p></td><td class="cl-7053869a"><p class="cl-70535ef4"><span class="cl-70535328">0.03</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td  colspan="3"class="cl-705386a4"><p class="cl-70535ee0"><span class="cl-70535328">Based on  31.35  hours of electrofishing effort</span></p></td></tr></tfoot></table></div></template>
<div class="flextable-shadow-host" id="38b40302-7ab0-4931-a17b-65ca402f5903"></div>
<script>
var dest = document.getElementById("38b40302-7ab0-4931-a17b-65ca402f5903");
var template = document.getElementById("4c3a6b2d-f903-4f6c-865d-e40e315f6923");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

```
</center>


<br><br>

```{=html}
<template id="fee1688d-5a57-4ac0-8ada-a0835c1cc1f8"><style>
.tabwid table{
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-spacing: 0;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-70690f42{table-layout:auto;border-collapse:collapse;width:50%;}.cl-706435b2{font-family:'Helvetica';font-size:14pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-706435da{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-706435e4{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7064420a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7064421e{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-70646960{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-70646974{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7064697e{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7064697f{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-70646988{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-70646992{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7064699c{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-70690f42'><thead><tr style="overflow-wrap:break-word;"><td  colspan="3"class="cl-70646988"><p class="cl-7064420a"><span class="cl-706435b2">Table 3. Native fish encounters within the<br> Tusher Reach, 2021</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7064699c"><p class="cl-7064420a"><span class="cl-706435da">Common Name</span></p></td><td class="cl-70646992"><p class="cl-7064421e"><span class="cl-706435da">Number of Fish Encountered</span></p></td><td class="cl-70646992"><p class="cl-7064421e"><span class="cl-706435da">Fish-per-Hour</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-70646974"><p class="cl-7064420a"><span class="cl-706435e4">bonytail [chub]</span></p></td><td class="cl-70646960"><p class="cl-7064421e"><span class="cl-706435e4">11</span></p></td><td class="cl-70646960"><p class="cl-7064421e"><span class="cl-706435e4">0.35</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7064697f"><p class="cl-7064420a"><span class="cl-706435e4">Colorado pikeminnow</span></p></td><td class="cl-7064697e"><p class="cl-7064421e"><span class="cl-706435e4">1</span></p></td><td class="cl-7064697e"><p class="cl-7064421e"><span class="cl-706435e4">0.03</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td  colspan="3"class="cl-70646988"><p class="cl-7064420a"><span class="cl-706435e4">Based on  31.35  hours of electrofishing effort</span></p></td></tr></tfoot></table></div></template>
<div class="flextable-shadow-host" id="9e12d6ff-cf50-4385-ac7f-e365781392b1"></div>
<script>
var dest = document.getElementById("9e12d6ff-cf50-4385-ac7f-e365781392b1");
var template = document.getElementById("fee1688d-5a57-4ac0-8ada-a0835c1cc1f8");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

```

<br><br>


```{=html}
<template id="3f99c03d-f6ca-41df-b3c4-962d3a34a1eb"><style>
.tabwid table{
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-spacing: 0;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-7079a758{table-layout:auto;border-collapse:collapse;width:60%;}.cl-7074a7bc{font-family:'Helvetica';font-size:14pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7074a7da{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7074a7e4{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7074b9fa{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7074ba0e{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-7074e06a{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7074e07e{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7074e088{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7074e092{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7074e09c{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7074e09d{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7074e0a6{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7074e0b0{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-7074e0b1{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-7079a758'><thead><tr style="overflow-wrap:break-word;"><td  colspan="4"class="cl-7074e0a6"><p class="cl-7074b9fa"><span class="cl-7074a7bc">Table 4. Walleye catch-per-unit-effort <br>Tusher Reach, 2017 - 2021</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7074e0b1"><p class="cl-7074b9fa"><span class="cl-7074a7da">Year</span></p></td><td class="cl-7074e0b0"><p class="cl-7074ba0e"><span class="cl-7074a7da">Number of Fish Encountered</span></p></td><td class="cl-7074e0b0"><p class="cl-7074ba0e"><span class="cl-7074a7da">Total Effort (hours)</span></p></td><td class="cl-7074e0b0"><p class="cl-7074ba0e"><span class="cl-7074a7da">Fish-per-Hour</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-7074e07e"><p class="cl-7074b9fa"><span class="cl-7074a7e4">2021</span></p></td><td class="cl-7074e06a"><p class="cl-7074ba0e"><span class="cl-7074a7e4">101</span></p></td><td class="cl-7074e06a"><p class="cl-7074ba0e"><span class="cl-7074a7e4">31.3</span></p></td><td class="cl-7074e06a"><p class="cl-7074ba0e"><span class="cl-7074a7e4">3.22</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7074e088"><p class="cl-7074b9fa"><span class="cl-7074a7e4">2020</span></p></td><td class="cl-7074e092"><p class="cl-7074ba0e"><span class="cl-7074a7e4">113</span></p></td><td class="cl-7074e092"><p class="cl-7074ba0e"><span class="cl-7074a7e4">39.7</span></p></td><td class="cl-7074e092"><p class="cl-7074ba0e"><span class="cl-7074a7e4">2.85</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7074e088"><p class="cl-7074b9fa"><span class="cl-7074a7e4">2019</span></p></td><td class="cl-7074e092"><p class="cl-7074ba0e"><span class="cl-7074a7e4">151</span></p></td><td class="cl-7074e092"><p class="cl-7074ba0e"><span class="cl-7074a7e4">43.4</span></p></td><td class="cl-7074e092"><p class="cl-7074ba0e"><span class="cl-7074a7e4">3.48</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7074e088"><p class="cl-7074b9fa"><span class="cl-7074a7e4">2018</span></p></td><td class="cl-7074e092"><p class="cl-7074ba0e"><span class="cl-7074a7e4">12</span></p></td><td class="cl-7074e092"><p class="cl-7074ba0e"><span class="cl-7074a7e4">7.2</span></p></td><td class="cl-7074e092"><p class="cl-7074ba0e"><span class="cl-7074a7e4">1.66</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-7074e09d"><p class="cl-7074b9fa"><span class="cl-7074a7e4">2017</span></p></td><td class="cl-7074e09c"><p class="cl-7074ba0e"><span class="cl-7074a7e4">32</span></p></td><td class="cl-7074e09c"><p class="cl-7074ba0e"><span class="cl-7074a7e4">25.0</span></p></td><td class="cl-7074e09c"><p class="cl-7074ba0e"><span class="cl-7074a7e4">1.28</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="4773fffd-382c-443a-937d-22c9602b8c2a"></div>
<script>
var dest = document.getElementById("4773fffd-382c-443a-937d-22c9602b8c2a");
var template = document.getElementById("3f99c03d-f6ca-41df-b3c4-962d3a34a1eb");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

```

<br><br>



<center>
![This chart has title 'Figure 3. Length frequency histogram for walleye  encountered within the Tusher Reach, 2021'. It has x-axis 'Total length (mm)' with labels 400, 500 and 600. It has y-axis 'Number of fish' with labels 0, 10 and 20. The chart is a bar chart with 12 vertical bars. It has colour set to black. The visualized data can be summarized as follows: Min.  =  345, 1st Qu.  =  430, Median  =  452, Mean  =  460, 3rd Qu.  =  478, Max.  =  613](123d_annual-rept_files/figure-html/lf-gr-fig-1.png)

```
## This chart has title 'Figure 3. Length frequency histogram for walleye
##  encountered within the Tusher Reach, 2021'.
## It has x-axis 'Total length (mm)' with labels 400, 500 and 600.
## It has y-axis 'Number of fish' with labels 0, 10 and 20.
## The chart is a bar chart with 12 vertical bars.
## It has colour set to black.
```
</center>

___

<br><br>

### Lower Gray Canyon Reach

Utah Division of Wildlife Resources completed an experimental two day removal pass in Lower Gray Canyon between 24 and 25 June 2020.  Noting a subtle increase in smallmouth bass within the Tusher reach and curious as to presence of walleye above the Tusher diversion we committed to a two-day raft-based removal pass. Crews encountered no walleye and only one smallmouth bass (Table 5) and few endangered fish (Table 6) within this reach. Researchers sampled between river miles  and  (Figure 1).

<br><br>



<br><br>





<br><br>

## Colorado River

<br><br>

<center>
<img src="/Users/christophermichaud/Documents/Projects/udwr-mfo_data-mgt/Reports/Assets/smallmouth-nick.jpg" title="A photograph showing eight ~300 mm smallmouth bass on a measuring board" alt="A photograph showing eight ~300 mm smallmouth bass on a measuring board" width="1452" />
</center>

Smallmouth bass removed from the swift narrows of Lower Westwater Canyon.

___

<br><br>

### Lower Westwater Reach

The Colorado River, at USGS gage 09180500, located near Cisco, UT, peaked at 8,300 cfs on 07 June 2021 (Figure 4).  Crews began sampling within Lower Westwater Canyon on  and ended on . Main channel temperatures ranged between °C during sampling (Table 1). Crews sampled between river miles  and (Figure 1).  During past years UDWR has encountered substantial numbers of walleye and smallmouth bass within this reach. Consequently, we monitor this reach under Project 123d and if walleye or smallmouth catch rates warrant, we apply additional removal effort.


<br><br>




<center>
![This chart has title 'Figure 4. Discharge on the Colorado River, 2021'. It has the subtitle 'Sampling events noted with blue points'. It has x-axis '' with labels Jan, Apr and Jul. It has y-axis 'Discharge (cfs)' with labels 2000, 4000, 6000 and 8000. It has 2 layers. Layer 1 is a set of 1 line. The line is broken or missing where NA values appear or where points exceed the plot boundaries. Line 1 connects 245 points. Layer 1 has size set to 1. Layer 2 is a set of 13 points. Layer 2 has shape set to fillable circle. Layer 2 has size set to 4. Layer 2 has fill set to brilliant blue. Layer 2 has alpha set to 0.8. This figure is depicts the dates on which sampling occurred (points) and the river discharge (line) during the sampling period.](123d_annual-rept_files/figure-html/unnamed-chunk-9-1.png)

```
## This chart has title 'Figure 4. Discharge on the Colorado River, 2021'.
## It has the subtitle 'Sampling events noted with blue points'.
## It has x-axis '' with labels Jan, Apr and Jul.
## It has y-axis 'Discharge (cfs)' with labels 2000, 4000, 6000 and 8000.
## It has 2 layers.
## Layer 1 is a set of 1 line.
## The line is broken or missing where NA values appear or where points exceed the plot boundaries.
## Line 1 connects 245 points.
## Layer 1 has size set to 1.
## Layer 2 is a set of 13 points.
## Layer 2 has shape set to fillable circle.
## Layer 2 has size set to 4.
## Layer 2 has fill set to brilliant blue.
## Layer 2 has alpha set to 0.8.
```

</center>

A total of  hours of effort was allocated to this reach and crews removed a total of  walleye (catch-per-unit-effort [cpue] =  fish-per-hour).  Additionally,  smallmouth bass were removed (cpue = ) within this reach (Table 7, Figure 5). This catch-rate is substantially higher than recent years (Table 9). This is particularly concerning due to the close proximity of the Westwater Canyon humpback chub population. Smallmouth bass mean total length in 2020 was NA mm (range = \infty{} - -\infty{} mm) (Figure 6). Ancillary captures of native species are noted in Table 8. 


<br><br>


```{=html}
<template id="d977c170-a81e-4358-9320-f4daa65e88fe"><style>
.tabwid table{
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-spacing: 0;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-7110f324{table-layout:auto;border-collapse:collapse;width:60%;}.cl-710c1458{font-family:'Helvetica';font-size:14pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-710c148a{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-710c1494{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-710c2272{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-710c2286{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-710c4f0e{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-710c4f22{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-710c4f2c{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-710c4f36{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-710c4f40{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-710c4f4a{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-710c4f4b{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-710c4f54{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-710c4f5e{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-7110f324'><thead><tr style="overflow-wrap:break-word;"><td  colspan="3"class="cl-710c4f4b"><p class="cl-710c2272"><span class="cl-710c1458">Table 7. Nonnative fish encounters within the <br>Lower Westwater Reach, 2021</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f54"><p class="cl-710c2272"><span class="cl-710c148a">Common Name</span></p></td><td class="cl-710c4f5e"><p class="cl-710c2286"><span class="cl-710c148a">Number of Fish Encountered</span></p></td><td class="cl-710c4f5e"><p class="cl-710c2286"><span class="cl-710c148a">Fish-per-Hour</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-710c4f22"><p class="cl-710c2272"><span class="cl-710c1494">smallmouth bass</span></p></td><td class="cl-710c4f0e"><p class="cl-710c2286"><span class="cl-710c1494">1,164</span></p></td><td class="cl-710c4f0e"><p class="cl-710c2286"><span class="cl-710c1494">26.78</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f36"><p class="cl-710c2272"><span class="cl-710c1494">green sunfish</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">110</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">2.53</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f36"><p class="cl-710c2272"><span class="cl-710c1494">gizzard shad</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">65</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">1.50</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f36"><p class="cl-710c2272"><span class="cl-710c1494">black bullhead</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">39</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">0.90</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f36"><p class="cl-710c2272"><span class="cl-710c1494">walleye</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">38</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">0.87</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f36"><p class="cl-710c2272"><span class="cl-710c1494">white sucker</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">17</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">0.39</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f36"><p class="cl-710c2272"><span class="cl-710c1494">largemouth bass</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">10</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">0.23</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f36"><p class="cl-710c2272"><span class="cl-710c1494">bluegill</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">3</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">0.07</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f36"><p class="cl-710c2272"><span class="cl-710c1494">flannelmouth sucker x white sucker</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">3</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">0.07</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f36"><p class="cl-710c2272"><span class="cl-710c1494">rainbow trout</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">1</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">0.02</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f36"><p class="cl-710c2272"><span class="cl-710c1494">striped bass</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">1</span></p></td><td class="cl-710c4f2c"><p class="cl-710c2286"><span class="cl-710c1494">0.02</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-710c4f40"><p class="cl-710c2272"><span class="cl-710c1494">yellow bullhead</span></p></td><td class="cl-710c4f4a"><p class="cl-710c2286"><span class="cl-710c1494">1</span></p></td><td class="cl-710c4f4a"><p class="cl-710c2286"><span class="cl-710c1494">0.02</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td  colspan="3"class="cl-710c4f4b"><p class="cl-710c2272"><span class="cl-710c1494">Based on  43.46  hours of electrofishing effort</span></p></td></tr></tfoot></table></div></template>
<div class="flextable-shadow-host" id="4ea27bd0-7b8c-4993-a1a8-1d7a493b15a4"></div>
<script>
var dest = document.getElementById("4ea27bd0-7b8c-4993-a1a8-1d7a493b15a4");
var template = document.getElementById("d977c170-a81e-4358-9320-f4daa65e88fe");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

```

<br><br>

```{=html}
<template id="c5675268-f4af-4f10-84f5-6801dc5afda4"><style>
.tabwid table{
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-spacing: 0;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-71244fa0{table-layout:auto;border-collapse:collapse;width:60%;}.cl-711edba6{font-family:'Helvetica';font-size:14pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-711edbc4{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-711edbc5{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-711eeda8{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-711eedbc{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-711f1bc0{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-711f1bd4{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-711f1bd5{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-711f1bde{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-711f1be8{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-711f1bf2{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-711f1bfc{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-711f1c06{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-711f1c07{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-71244fa0'><thead><tr style="overflow-wrap:break-word;"><td  colspan="3"class="cl-711f1bfc"><p class="cl-711eeda8"><span class="cl-711edba6">Table 8. Native fish encounters within the <br>Lower Westwater Reach, 2021</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-711f1c07"><p class="cl-711eeda8"><span class="cl-711edbc4">Common Name</span></p></td><td class="cl-711f1c06"><p class="cl-711eedbc"><span class="cl-711edbc4">Number of Fish Encountered</span></p></td><td class="cl-711f1c06"><p class="cl-711eedbc"><span class="cl-711edbc4">Fish-per-Hour</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-711f1bd4"><p class="cl-711eeda8"><span class="cl-711edbc5">roundtail chub</span></p></td><td class="cl-711f1bc0"><p class="cl-711eedbc"><span class="cl-711edbc5">22</span></p></td><td class="cl-711f1bc0"><p class="cl-711eedbc"><span class="cl-711edbc5">0.51</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-711f1bde"><p class="cl-711eeda8"><span class="cl-711edbc5">Colorado pikeminnow</span></p></td><td class="cl-711f1bd5"><p class="cl-711eedbc"><span class="cl-711edbc5">14</span></p></td><td class="cl-711f1bd5"><p class="cl-711eedbc"><span class="cl-711edbc5">0.32</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-711f1bde"><p class="cl-711eeda8"><span class="cl-711edbc5">native Gila not identified to species</span></p></td><td class="cl-711f1bd5"><p class="cl-711eedbc"><span class="cl-711edbc5">10</span></p></td><td class="cl-711f1bd5"><p class="cl-711eedbc"><span class="cl-711edbc5">0.23</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-711f1bde"><p class="cl-711eeda8"><span class="cl-711edbc5">razorback sucker</span></p></td><td class="cl-711f1bd5"><p class="cl-711eedbc"><span class="cl-711edbc5">4</span></p></td><td class="cl-711f1bd5"><p class="cl-711eedbc"><span class="cl-711edbc5">0.09</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-711f1bf2"><p class="cl-711eeda8"><span class="cl-711edbc5">bonytail [chub]</span></p></td><td class="cl-711f1be8"><p class="cl-711eedbc"><span class="cl-711edbc5">2</span></p></td><td class="cl-711f1be8"><p class="cl-711eedbc"><span class="cl-711edbc5">0.05</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td  colspan="3"class="cl-711f1bfc"><p class="cl-711eeda8"><span class="cl-711edbc5">Based on  43.46  hours of electrofishing effort</span></p></td></tr></tfoot></table></div></template>
<div class="flextable-shadow-host" id="7aea273a-1268-44da-8d59-03f5a0efd626"></div>
<script>
var dest = document.getElementById("7aea273a-1268-44da-8d59-03f5a0efd626");
var template = document.getElementById("c5675268-f4af-4f10-84f5-6801dc5afda4");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

```

<br><br>

```{=html}
<template id="89ec7de7-1bf6-41cf-8cea-2ca925feb1e3"><style>
.tabwid table{
  border-collapse:collapse;
  line-height:1;
  margin-left:auto;
  margin-right:auto;
  border-width: 0;
  display: table;
  margin-top: 1.275em;
  margin-bottom: 1.275em;
  border-spacing: 0;
  border-color: transparent;
}
.tabwid_left table{
  margin-left:0;
}
.tabwid_right table{
  margin-right:0;
}
.tabwid td {
    padding: 0;
}
.tabwid a {
  text-decoration: none;
}
.tabwid thead {
    background-color: transparent;
}
.tabwid tfoot {
    background-color: transparent;
}
.tabwid table tr {
background-color: transparent;
}
</style><div class="tabwid"><style>.cl-71386896{table-layout:auto;border-collapse:collapse;width:60%;}.cl-71312f7c{font-family:'Helvetica';font-size:14pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-71312f9a{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-71312fa4{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-7131439a{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-713143b8{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-71317ad6{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71317aea{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71317af4{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71317afe{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71317aff{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71317b08{background-color:transparent;vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 0.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71317b12{background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(255, 255, 255, 0.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71317b1c{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-71317b1d{background-color:rgba(211, 211, 211, 1.00);vertical-align: middle;border-bottom: 2pt solid rgba(102, 102, 102, 1.00);border-top: 2pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table class='cl-71386896'><thead><tr style="overflow-wrap:break-word;"><td  colspan="4"class="cl-71317b12"><p class="cl-7131439a"><span class="cl-71312f7c">Table 9. Smallmouth bass catch-per-unit-effort <br>Lower Westwater Reach, 2017 - 2021</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-71317b1d"><p class="cl-7131439a"><span class="cl-71312f9a">Year</span></p></td><td class="cl-71317b1c"><p class="cl-713143b8"><span class="cl-71312f9a">Number of Fish Encountered</span></p></td><td class="cl-71317b1c"><p class="cl-713143b8"><span class="cl-71312f9a">Total Effort (hours)</span></p></td><td class="cl-71317b1c"><p class="cl-713143b8"><span class="cl-71312f9a">Fish-per-Hour</span></p></td></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-71317aea"><p class="cl-7131439a"><span class="cl-71312fa4">2021</span></p></td><td class="cl-71317ad6"><p class="cl-713143b8"><span class="cl-71312fa4">1,164</span></p></td><td class="cl-71317ad6"><p class="cl-713143b8"><span class="cl-71312fa4">43.5</span></p></td><td class="cl-71317ad6"><p class="cl-713143b8"><span class="cl-71312fa4">26.78</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-71317af4"><p class="cl-7131439a"><span class="cl-71312fa4">2020</span></p></td><td class="cl-71317afe"><p class="cl-713143b8"><span class="cl-71312fa4">369</span></p></td><td class="cl-71317afe"><p class="cl-713143b8"><span class="cl-71312fa4">19.7</span></p></td><td class="cl-71317afe"><p class="cl-713143b8"><span class="cl-71312fa4">18.69</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-71317af4"><p class="cl-7131439a"><span class="cl-71312fa4">2019</span></p></td><td class="cl-71317afe"><p class="cl-713143b8"><span class="cl-71312fa4">12</span></p></td><td class="cl-71317afe"><p class="cl-713143b8"><span class="cl-71312fa4">6.6</span></p></td><td class="cl-71317afe"><p class="cl-713143b8"><span class="cl-71312fa4">1.81</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-71317af4"><p class="cl-7131439a"><span class="cl-71312fa4">2018</span></p></td><td class="cl-71317afe"><p class="cl-713143b8"><span class="cl-71312fa4">5</span></p></td><td class="cl-71317afe"><p class="cl-713143b8"><span class="cl-71312fa4">2.0</span></p></td><td class="cl-71317afe"><p class="cl-713143b8"><span class="cl-71312fa4">2.45</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-71317b08"><p class="cl-7131439a"><span class="cl-71312fa4">2017</span></p></td><td class="cl-71317aff"><p class="cl-713143b8"><span class="cl-71312fa4">35</span></p></td><td class="cl-71317aff"><p class="cl-713143b8"><span class="cl-71312fa4">7.0</span></p></td><td class="cl-71317aff"><p class="cl-713143b8"><span class="cl-71312fa4">4.96</span></p></td></tr></tbody></table></div></template>
<div class="flextable-shadow-host" id="71319190-19ea-42cb-9e64-83fe06b58245"></div>
<script>
var dest = document.getElementById("71319190-19ea-42cb-9e64-83fe06b58245");
var template = document.getElementById("89ec7de7-1bf6-41cf-8cea-2ca925feb1e3");
var caption = template.content.querySelector("caption");
if(caption) {
  caption.style.cssText = "display:block;text-align:center;";
  var newcapt = document.createElement("p");
  newcapt.appendChild(caption)
  dest.parentNode.insertBefore(newcapt, dest.previousSibling);
}
var fantome = dest.attachShadow({mode: 'open'});
var templateContent = template.content;
fantome.appendChild(templateContent);
</script>

```

<br><br>



<center>

</center>

<br><br>




<center>


</center>

<br><br>

___


## Bureau of Reclamation Information

### COLORADO RIVER RECOVERY PROGRAM			RECOVERY PROGRAM
### FY 2021 ANNUAL PROJECT REPORT				PROJECT NUMBER: <u> 123d </u>

I.	Project Title: Walleye control in the Lower Green and Colorado Rivers.

II.	Bureau of Reclamation Agreement Number(s): <br><br> 
  UDWR Moab: R19AP00059 <br>                                                 
  Project/Grant Period:  
  Start date (Mo/Day/Yr): 10/01/2018  
  End date: (Mo/Day/Yr): 09/30/2023  
  Reporting period end date: 09/30/2020  
  Is this the final report? Yes __ No  <u> X </u> <br><br>
  
  
III.	Principal Investigator(s): <br><br>
  Chris Michaud  
  Utah Division of Wildlife Resources  
  1165 S Hwy 191, Suite 4, 
  Moab, UT 84532  
  Phone: 435-259-3784;  
  E-mail: cmichaud@utah.gov <br><br>


IV.	Abstract: <br><br>
Utah Division of Wildlife Resources (UDWR, Moab, UT) expended 74.9 hours of electrofishing effort under Project 123d to remove nonnative walleye from the upper Colorado River Basin in 2021. Crews focused removal efforts within specific subreaches where walleye catch rates are highest: downstream of Tusher Diversion (River Mile (RM)  - ) and Lower Gray Canyon (RM  - ) on the Green River and Lower Westwater Canyon (RM  - ) on the Colorado River. A total of 0 walleye and 0 smallmouth bass were encountered throughout sampling in 2021. While walleye encounters were similar to recent years, smallmouth bass captures on the Lower Colorado River were substantially more frequent. <br><br>


V.	Study Schedule: <br><br>
2014-ongoing <br><br>

VI.	Relationship to RIPRAP: <br>  
GENERAL RECOVERY PROGRAM SUPPORT ACTION PLAN   
Reduce negative impacts of nonnative fishes and sportfish management 
activities (nonnative and sportfish management).  
Reduce negative interactions between nonnative and endangered fishes.  
Identify and implement viable active control measures. <br>  
GREEN RIVER ACTION PLAN: MAINSTEM  
Reduce impacts of nonnative fishes and sportfish management activities 
(nonnative and sportfish management).  
Reduce negative impacts to endangered fishes from sportfish management
activities.  
Develop and implement control programs for nonnative fishes in river reaches
occupied by the endangered fishes to identify required levels of control. Each
control activity will be evaluated for effectiveness, and then continued as needed. <br>  
COLORADO RIVER ACTION PLAN: MAINSTEM  
Reduce impacts of nonnative fishes and sportfish management activities
(nonnative and sportfish management).  
Reduce negative interactions between nonnative and endangered fishes.  
Develop basinwide aquatic management plan to reduce nonnative fish impacts
while providing sportfishing opportunities. <br><br>

VII.	Accomplishment of FY 2020 Tasks and Deliverables, Discussion of Initial Findings and Shortcomings: <br><br>
See reach specific analysis tabs <br><br>

VIII.	Additional noteworthy observations: <br><br>
See reach specific analysis tabs <br><br>

IX.	Recommendations: <br><br>  

    * **Tusher Reach (Green River)**  
  Continued application of effort between Tusher Diversion and Green River
  State Park (RM 128-120) as this segment has the highest catch rates for walleye in
  the reach. Removal should be conducted spring through early summer, or when justified by 
  noteworthy catch rates. <br><br> 

    * **Lower Grey Canyon (Green River)**  
  Targeted walleye removal within this reach is not warranted at present time. Monitor through project 
  123a (Deso bass removal) efforts when appropriate. <br><br>
  
    * **Lower Westwater Canyon (Colorado River)**  
  Continued application of effort between Big Hole camp and Fish Ford (RM 116-105.5). Removal should be 
  conducted spring through early summer, or when justified by noteworthy catch rates of walleye *or* 
  smallmouth bass. <br><br>

X.	Project Status: <br><br>
On track and ongoing <br><br>

XI.	FY 2020 Budget Status

	A.	Funds Provided: $53,697
	B.	Funds Expended: $53,697
	C.	Difference:  $0
	D.	Percent of the FY 2020 work completed, and projected costs to complete: 100%
	E.	Recovery Program funds spent for publication charges: $0  <br><br>

XII.	Status of Data Submission: <br><br> 
Data will be uploaded into STReaMs by the end of January 2021. <br><br>

XIII.	Signed:	<br>                                  		          
Principal Investigator: <u> Christopher Michaud </u>	&nbsp;&nbsp;&nbsp;&nbsp;	Date: <u> 11/1/2020 </u>

<br><br>
